{
  "hash": "bf3be99243558f37e35489861269792a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 4: Prototyping Modules for Visual Analytics Shiny Application\"\ndate: \"March 1, 2024\"\ndate-modified: \"last-modified\"\ntoc: true\nexecute:\n  eval: true\n  echo: true\n  freeze: true\n  warning: false\n  message: false\neditor: visual\n---\n\n\n## 1. The Task\n\nIn this take-home exercise, I am required to select one of the module of my group's proposed Shiny application and complete the following tasks:\n\n-   To evaluate and determine the necessary R packages needed for the Shiny application and ensure that they are supported in R CRAN,\n\n-   To prepare and test the specific R codes to ensure that they can run and return the correct output as expected,\n\n-   To determine the parameters and outputs that will be exposed on the Shiny applications, and\n\n-   To select the appropriate Shiny UI components for exposing the parameters determined above.\n\nAll teams must consult the [prototype](https://habaritanzania.netlify.app/) page of [AY2022-2023 January Term Group 3: Tanzania Tourism Analysis](https://thehabaritanzania.netlify.app/). There are three main modules in this application: [Exploratory Data Analysis](https://habaritanzania.netlify.app/eda/eda) & [Confirmatory Data Analysis](https://habaritanzania.netlify.app/eda/cda), [Cluster Analysis](https://habaritanzania.netlify.app/analysis/clustering) and [Decision Tree Analysis](https://habaritanzania.netlify.app/analysis/decision_tree). Each of them were prepared by one of the member of the project team which they later combined into the Prototype page of their project website.\n\nTake-home Exercise 4 will be similar to one of the prototype module prepared above in term of content but with the following differences:\n\n-   I am required to prepare the prototype module report as Take-home Exercise 4 submission. This mean, it has to be published on my own coursework page.\n\n-   I am required to include a section called UI design for the different components of the UIs for the proposed design.\n\nFor storyboarding the UI Design, I will need to consult [Storyboard](https://giniceseah.netlify.app/posts/2021-07-31-storyboard/) link.\n\n## 2. About the Project\n\nMy project group [StormTroopers](https://vaastormtroopers.netlify.app/proposal/proposal) is working on the topic of climate change.\n\nAs a small, low-lying city-state, Singapore is vulnerable to the effects of climate change which has brought about more extreme weather patterns - rising sea levels, dry spells and intense rainfall which at times can lead to flash floods.\n\n![](images/clipboard-939414320.png)\n\nAcording to an [infographic](https://www.nccs.gov.sg/singapores-climate-action/impact-of-climate-change-in-singapore/) above by the National Climate Change Secretariat Singapore:\n\n1.  Daily mean temperatures are projected to increase by 1.4 to 4.6 degrees celsius; and\n2.  The contrast between the wet months (November to January) and dry months (February and June to September) is likely to be more pronounced.\n\nIn Jan 2024, the Centre for Climate Research Singapore (CCRS) announced the [Third National Climate Change Study (V3)](https://www.mss-int.sg/v3-climate-projections) which provided potential scenarios of our future based on low, medium, and high global greenhouse gas emissions.\n\n1.  Very hot days will become more frequent.\n2.  Extreme daily rainfall is projected to intensify.\n3.  The mean sea level around Singapore is projected to rise up to 1.15m by end century, and up to around 2m by 2150 under the high emissions scenario.\n\nIt is important that we better understand how climate change has been affecting Singapore, by understanding the trends in our daily temperatures and rainfall over the years, and utilise historical data to forecast future climate data. It will provide guidance on whether and how Singapore will need to urgently develop ways to mitigate and adapt.\n\n### 2.1 Issues to address\n\nThe scope I am in charge of is Confirmatory Data Analysis (CDA) which seeks to address the following issues:\n\n-   Are the changes in rainfall and temperature over the years statistically significant? \n\n-   Are there really certain months “drier” or “wetter”/ “hotter” or “cooler”?\n\n-   Are there certain locations “drier” or “wetter”/ “hotter” or “cooler”?\n\n## 3. The Data\n\nFor this take-home exercise and the project, data utilised is the historical climate data from [Metrological Service Singapore](http://www.weather.gov.sg/climate-historical-daily).\n\nThe team downloaded historical daily records from various weather stations across Singapore from 1980 to 2023 via API scrapping as a *daily_historical.csv* datafile.\n\n## 4. Set-up\n\n### 4.1 Installing and loading the required libraries\n\nThe following code chunk is used to install the necessary R packages:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(tidyverse,ggridges,ggrepel,ggthemes,ggstatsplot,hrbrthemes,patchwork,dplyr, gifski, gapminder,plotly,gganimate,ggiraph,magick)\n```\n:::\n\n\n### 4.2 Importing the Dataset\n\nI will import the *daily_historical.csv* datafile using the following code chunk:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaily_historical <- read_csv(\"data/daily_historical.csv\",locale=locale(encoding=\"latin1\"))\n\ndaily_historical\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 329,156 × 13\n   station          year month   day daily_rainfall_total highest_30_min_rainf…¹\n   <chr>           <dbl> <dbl> <dbl>                <dbl>                  <dbl>\n 1 Macritchie Res…  1980     1     1                  0                       NA\n 2 Macritchie Res…  1980     1     2                  0                       NA\n 3 Macritchie Res…  1980     1     3                  0                       NA\n 4 Macritchie Res…  1980     1     4                  0                       NA\n 5 Macritchie Res…  1980     1     5                 22.6                     NA\n 6 Macritchie Res…  1980     1     6                 49.6                     NA\n 7 Macritchie Res…  1980     1     7                  2.4                     NA\n 8 Macritchie Res…  1980     1     8                  0                       NA\n 9 Macritchie Res…  1980     1     9                  0                       NA\n10 Macritchie Res…  1980     1    10                  0                       NA\n# ℹ 329,146 more rows\n# ℹ abbreviated name: ¹​highest_30_min_rainfall\n# ℹ 7 more variables: highest_60_min_rainfall <dbl>,\n#   highest_120_min_rainfall <dbl>, mean_temperature <dbl>,\n#   maximum_temperature <dbl>, minimum_temperature <dbl>,\n#   mean_wind_speed <dbl>, max_wind_speed <dbl>\n```\n\n\n:::\n:::\n\n\nAs can be seen, there are a total of 329,156 records across 13 variables.\n\n### 4.3 Data Cleaning\n\n#### 4.3.1 Remove missing values\n\nBefore proceeding with analysis, we first remove any missing values in the data using the following code chunk:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaily_historical <- drop_na(daily_historical)\n\ndaily_historical\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 44,856 × 13\n   station    year month   day daily_rainfall_total highest_30_min_rainfall\n   <chr>     <dbl> <dbl> <dbl>                <dbl>                   <dbl>\n 1 Admiralty  2014     1     1                  0                       0  \n 2 Admiralty  2014     1     2                  0                       0  \n 3 Admiralty  2014     1     3                  4.6                     4.4\n 4 Admiralty  2014     1     4                  3.8                     3.8\n 5 Admiralty  2014     1     5                  3.6                     1.2\n 6 Admiralty  2014     1     6                 80                      21.8\n 7 Admiralty  2014     1     7                  2                       2  \n 8 Admiralty  2014     1     8                  0                       0  \n 9 Admiralty  2014     1     9                  2.6                     1.4\n10 Admiralty  2014     1    10                  0                       0  \n# ℹ 44,846 more rows\n# ℹ 7 more variables: highest_60_min_rainfall <dbl>,\n#   highest_120_min_rainfall <dbl>, mean_temperature <dbl>,\n#   maximum_temperature <dbl>, minimum_temperature <dbl>,\n#   mean_wind_speed <dbl>, max_wind_speed <dbl>\n```\n\n\n:::\n:::\n\n\nAs can be seen, what remains is a total of 44,856 records across 13 variables.\n\n#### 4.3.2 Ensuring alignment in time period of records across weather stations\n\nTo ensure consistent comparison across all weather stations, the same time period would have to be used. As such, we need to check the starting and ending year of data across all weather stations:\n\n::: panel-tabset\n## Starting Year\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaily_historical_start <- daily_historical %>% \n  group_by(station) %>% \n  summarise(earliest_year = min(year))\n\ndaily_historical_start\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 13 × 2\n   station               earliest_year\n   <chr>                         <dbl>\n 1 Admiralty                      2014\n 2 Ang Mo Kio                     2014\n 3 Changi                         2014\n 4 Choa Chu Kang (South)          2014\n 5 Clementi                       2014\n 6 East Coast Parkway             2014\n 7 Jurong (West)                  2014\n 8 Jurong Island                  2014\n 9 Newton                         2014\n10 Pasir Panjang                  2014\n11 Sentosa Island                 2014\n12 Tai Seng                       2014\n13 Tuas South                     2014\n```\n\n\n:::\n:::\n\n\n## Ending Year\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaily_historical_start <- daily_historical %>%\n  group_by(station) %>%\n  summarise(latest_year = max(year))\n\ndaily_historical_start\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 13 × 2\n   station               latest_year\n   <chr>                       <dbl>\n 1 Admiralty                    2023\n 2 Ang Mo Kio                   2023\n 3 Changi                       2023\n 4 Choa Chu Kang (South)        2023\n 5 Clementi                     2023\n 6 East Coast Parkway           2023\n 7 Jurong (West)                2023\n 8 Jurong Island                2023\n 9 Newton                       2023\n10 Pasir Panjang                2023\n11 Sentosa Island               2023\n12 Tai Seng                     2023\n13 Tuas South                   2023\n```\n\n\n:::\n:::\n\n:::\n\n```         \n```\n\nAs the starting and ending year of weather data across all 13 weather stations is 2014 and 2023 respectively, no further steps are required to align the time period of the data.\n\n#### 4.3.3 Converting data types for *year*, *month* and *day*\n\nBased on a *glimpse* of the *daily_historical* dataframe, the data types for *year*, *month* and *day* are continuous.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(daily_historical)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 44,856\nColumns: 13\n$ station                  <chr> \"Admiralty\", \"Admiralty\", \"Admiralty\", \"Admir…\n$ year                     <dbl> 2014, 2014, 2014, 2014, 2014, 2014, 2014, 201…\n$ month                    <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …\n$ day                      <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14…\n$ daily_rainfall_total     <dbl> 0.0, 0.0, 4.6, 3.8, 3.6, 80.0, 2.0, 0.0, 2.6,…\n$ highest_30_min_rainfall  <dbl> 0.0, 0.0, 4.4, 3.8, 1.2, 21.8, 2.0, 0.0, 1.4,…\n$ highest_60_min_rainfall  <dbl> 0.0, 0.0, 4.4, 3.8, 1.6, 26.2, 2.0, 0.0, 2.0,…\n$ highest_120_min_rainfall <dbl> 0.0, 0.0, 4.6, 3.8, 2.0, 30.6, 2.0, 0.0, 2.6,…\n$ mean_temperature         <dbl> 26.3, 26.9, 26.5, 26.4, 24.6, 25.0, 26.5, 26.…\n$ maximum_temperature      <dbl> 28.8, 30.7, 29.5, 31.2, 25.3, 27.2, 30.6, 30.…\n$ minimum_temperature      <dbl> 24.3, 24.6, 24.9, 24.7, 23.6, 23.1, 24.3, 24.…\n$ mean_wind_speed          <dbl> 10.8, 11.5, 9.7, 8.1, 8.4, 6.2, 8.0, 11.7, 6.…\n$ max_wind_speed           <dbl> 34.2, 38.2, 34.2, 32.8, 27.0, 29.5, 27.4, 34.…\n```\n\n\n:::\n:::\n\n\nFor ease of further analysis, we will convert them to categorical *factor* data type instead:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaily_historical <- daily_historical %>%\n  mutate_at(vars(year,month,day),as.factor)\n\nglimpse(daily_historical)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 44,856\nColumns: 13\n$ station                  <chr> \"Admiralty\", \"Admiralty\", \"Admiralty\", \"Admir…\n$ year                     <fct> 2014, 2014, 2014, 2014, 2014, 2014, 2014, 201…\n$ month                    <fct> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …\n$ day                      <fct> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14…\n$ daily_rainfall_total     <dbl> 0.0, 0.0, 4.6, 3.8, 3.6, 80.0, 2.0, 0.0, 2.6,…\n$ highest_30_min_rainfall  <dbl> 0.0, 0.0, 4.4, 3.8, 1.2, 21.8, 2.0, 0.0, 1.4,…\n$ highest_60_min_rainfall  <dbl> 0.0, 0.0, 4.4, 3.8, 1.6, 26.2, 2.0, 0.0, 2.0,…\n$ highest_120_min_rainfall <dbl> 0.0, 0.0, 4.6, 3.8, 2.0, 30.6, 2.0, 0.0, 2.6,…\n$ mean_temperature         <dbl> 26.3, 26.9, 26.5, 26.4, 24.6, 25.0, 26.5, 26.…\n$ maximum_temperature      <dbl> 28.8, 30.7, 29.5, 31.2, 25.3, 27.2, 30.6, 30.…\n$ minimum_temperature      <dbl> 24.3, 24.6, 24.9, 24.7, 23.6, 23.1, 24.3, 24.…\n$ mean_wind_speed          <dbl> 10.8, 11.5, 9.7, 8.1, 8.4, 6.2, 8.0, 11.7, 6.…\n$ max_wind_speed           <dbl> 34.2, 38.2, 34.2, 32.8, 27.0, 29.5, 27.4, 34.…\n```\n\n\n:::\n:::\n\n\n### 4.4 Data Wrangling\n\nWe will analyse weather and rainfall data separately and hence we will create two dataframes *historical_weather* and *historical_rainfall* from the dataset *daily_historical:*\n\n::: panel-tabset\n## *historical_weather*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhistorical_weather <- daily_historical %>% select(1:4,9:11)\nhistorical_weather\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 44,856 × 7\n   station   year  month day   mean_temperature maximum_temperature\n   <chr>     <fct> <fct> <fct>            <dbl>               <dbl>\n 1 Admiralty 2014  1     1                 26.3                28.8\n 2 Admiralty 2014  1     2                 26.9                30.7\n 3 Admiralty 2014  1     3                 26.5                29.5\n 4 Admiralty 2014  1     4                 26.4                31.2\n 5 Admiralty 2014  1     5                 24.6                25.3\n 6 Admiralty 2014  1     6                 25                  27.2\n 7 Admiralty 2014  1     7                 26.5                30.6\n 8 Admiralty 2014  1     8                 26.9                30.8\n 9 Admiralty 2014  1     9                 25.4                27.5\n10 Admiralty 2014  1     10                26.9                31.9\n# ℹ 44,846 more rows\n# ℹ 1 more variable: minimum_temperature <dbl>\n```\n\n\n:::\n:::\n\n\n## *historical_rainfall*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhistorical_rainfall <- daily_historical %>% select(1:8)\nhistorical_rainfall\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 44,856 × 8\n   station   year  month day   daily_rainfall_total highest_30_min_rainfall\n   <chr>     <fct> <fct> <fct>                <dbl>                   <dbl>\n 1 Admiralty 2014  1     1                      0                       0  \n 2 Admiralty 2014  1     2                      0                       0  \n 3 Admiralty 2014  1     3                      4.6                     4.4\n 4 Admiralty 2014  1     4                      3.8                     3.8\n 5 Admiralty 2014  1     5                      3.6                     1.2\n 6 Admiralty 2014  1     6                     80                      21.8\n 7 Admiralty 2014  1     7                      2                       2  \n 8 Admiralty 2014  1     8                      0                       0  \n 9 Admiralty 2014  1     9                      2.6                     1.4\n10 Admiralty 2014  1     10                     0                       0  \n# ℹ 44,846 more rows\n# ℹ 2 more variables: highest_60_min_rainfall <dbl>,\n#   highest_120_min_rainfall <dbl>\n```\n\n\n:::\n:::\n\n:::\n\n## 5. CDA\n\n### 5.1 CDA #1 - Are the changes in rainfall and temperature over the years statistically significant? \n\nThe first CDA that I will address is whether changes in rainfall and temperature over the years are statistically significant\n\nAs the data ranges from 2014 to 2023, there are 10 years worth of data.\n\n### 5.1.1 Historical rainfall over the years\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhistorical_rainfall_year <- historical_rainfall %>%\n  group_by(station,year) %>%\n  summarise(yearly_rainfall = sum(daily_rainfall_total))\n\nhistorical_rainfall_year\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 130 × 3\n# Groups:   station [13]\n   station   year  yearly_rainfall\n   <chr>     <fct>           <dbl>\n 1 Admiralty 2014            1808.\n 2 Admiralty 2015            2047.\n 3 Admiralty 2016            1962.\n 4 Admiralty 2017            1914.\n 5 Admiralty 2018            2212.\n 6 Admiralty 2019            1969.\n 7 Admiralty 2020            2015 \n 8 Admiralty 2021            2552.\n 9 Admiralty 2022            3164.\n10 Admiralty 2023            2589.\n# ℹ 120 more rows\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot(historical_rainfall_year,\n             aes(y=yearly_rainfall,\n                 x = year,\n                 group = station,\n                 color = station)) +\n  geom_line() +\n  facet_wrap(~station,scales = \"free_x\") +\n  labs(title=\"Yearly rainfall across weather stations from 2014 to 2023\",\n       y = \"Rainfall volume (mm)\",\n       x = \"Year\") +\n  theme_minimal() +\n  theme(axis.text.x=element_text(angle=90,hjust=1))\n\np1 <- ggplotly(p1, tooltip=\"all\",width = 800,height = 600) %>% \n  layout(width = 800, height = 600)\n\np1\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"htmlwidget-0620e2dec50fbb9b5a5c\" style=\"width:100%;height:487px;\" class=\"plotly html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-0620e2dec50fbb9b5a5c\">{\"x\":{\"data\":[{\"x\":[1,2,3,4,5,6,7,8,9,10],\"y\":[1807.9000000000001,2046.8,1961.5999999999999,1914.2,2211.6999999999998,1969.4000000000001,2015,2551.8000000000002,3163.9000000000001,2588.8000000000002],\"text\":[\"year: 2014<br />yearly_rainfall: 1807.9<br />station: Admiralty<br />station: Admiralty\",\"year: 2015<br />yearly_rainfall: 2046.8<br />station: Admiralty<br />station: Admiralty\",\"year: 2016<br />yearly_rainfall: 1961.6<br />station: Admiralty<br />station: Admiralty\",\"year: 2017<br />yearly_rainfall: 1914.2<br />station: Admiralty<br />station: Admiralty\",\"year: 2018<br />yearly_rainfall: 2211.7<br />station: Admiralty<br />station: Admiralty\",\"year: 2019<br />yearly_rainfall: 1969.4<br />station: Admiralty<br />station: Admiralty\",\"year: 2020<br />yearly_rainfall: 2015.0<br />station: Admiralty<br />station: Admiralty\",\"year: 2021<br />yearly_rainfall: 2551.8<br />station: Admiralty<br />station: Admiralty\",\"year: 2022<br />yearly_rainfall: 3163.9<br />station: Admiralty<br />station: Admiralty\",\"year: 2023<br />yearly_rainfall: 2588.8<br />station: Admiralty<br />station: Admiralty\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(248,118,109,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Admiralty\",\"legendgroup\":\"Admiralty\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1,2,3,4,5,6,7,8,9,10],\"y\":[1961.4000000000001,2018.4000000000001,2193.4000000000001,2573,2734.5999999999999,1624.4000000000001,2279.5,3126.5999999999999,3207.5999999999999,2889.8000000000002],\"text\":[\"year: 2014<br />yearly_rainfall: 1961.4<br />station: Ang Mo Kio<br />station: Ang Mo Kio\",\"year: 2015<br />yearly_rainfall: 2018.4<br />station: Ang Mo Kio<br />station: Ang Mo Kio\",\"year: 2016<br />yearly_rainfall: 2193.4<br />station: Ang Mo Kio<br />station: Ang Mo Kio\",\"year: 2017<br />yearly_rainfall: 2573.0<br />station: Ang Mo Kio<br />station: Ang Mo Kio\",\"year: 2018<br />yearly_rainfall: 2734.6<br />station: Ang Mo Kio<br />station: Ang Mo Kio\",\"year: 2019<br />yearly_rainfall: 1624.4<br />station: Ang Mo Kio<br />station: Ang Mo Kio\",\"year: 2020<br />yearly_rainfall: 2279.5<br />station: Ang Mo Kio<br />station: Ang Mo Kio\",\"year: 2021<br />yearly_rainfall: 3126.6<br />station: Ang Mo Kio<br />station: Ang Mo Kio\",\"year: 2022<br />yearly_rainfall: 3207.6<br />station: Ang Mo Kio<br />station: Ang Mo Kio\",\"year: 2023<br />yearly_rainfall: 2889.8<br />station: Ang Mo Kio<br />station: Ang Mo Kio\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(225,138,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Ang Mo Kio\",\"legendgroup\":\"Ang Mo Kio\",\"showlegend\":true,\"xaxis\":\"x2\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1,2,3,4,5,6,7,8,9,10],\"y\":[1538.4000000000001,1266.8,1954,2040.8,1708.2,1367.5,1793.2,2796.5999999999999,2169,2411.1999999999998],\"text\":[\"year: 2014<br />yearly_rainfall: 1538.4<br />station: Changi<br />station: Changi\",\"year: 2015<br />yearly_rainfall: 1266.8<br />station: Changi<br />station: Changi\",\"year: 2016<br />yearly_rainfall: 1954.0<br />station: Changi<br />station: Changi\",\"year: 2017<br />yearly_rainfall: 2040.8<br />station: Changi<br />station: Changi\",\"year: 2018<br />yearly_rainfall: 1708.2<br />station: Changi<br />station: Changi\",\"year: 2019<br />yearly_rainfall: 1367.5<br />station: Changi<br />station: Changi\",\"year: 2020<br />yearly_rainfall: 1793.2<br />station: Changi<br />station: Changi\",\"year: 2021<br />yearly_rainfall: 2796.6<br />station: Changi<br />station: Changi\",\"year: 2022<br />yearly_rainfall: 2169.0<br />station: Changi<br />station: Changi\",\"year: 2023<br />yearly_rainfall: 2411.2<br />station: Changi<br />station: Changi\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(190,156,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Changi\",\"legendgroup\":\"Changi\",\"showlegend\":true,\"xaxis\":\"x3\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1,2,3,4,5,6,7,8,9,10],\"y\":[2210.8000000000002,1666.2,2597.8000000000002,2035,2742,2136.6999999999998,2664.1999999999998,3448.1999999999998,2866.5999999999999,3263.5999999999999],\"text\":[\"year: 2014<br />yearly_rainfall: 2210.8<br />station: Choa Chu Kang (South)<br />station: Choa Chu Kang (South)\",\"year: 2015<br />yearly_rainfall: 1666.2<br />station: Choa Chu Kang (South)<br />station: Choa Chu Kang (South)\",\"year: 2016<br />yearly_rainfall: 2597.8<br />station: Choa Chu Kang (South)<br />station: Choa Chu Kang (South)\",\"year: 2017<br />yearly_rainfall: 2035.0<br />station: Choa Chu Kang (South)<br />station: Choa Chu Kang (South)\",\"year: 2018<br />yearly_rainfall: 2742.0<br />station: Choa Chu Kang (South)<br />station: Choa Chu Kang (South)\",\"year: 2019<br />yearly_rainfall: 2136.7<br />station: Choa Chu Kang (South)<br />station: Choa Chu Kang (South)\",\"year: 2020<br />yearly_rainfall: 2664.2<br />station: Choa Chu Kang (South)<br />station: Choa Chu Kang (South)\",\"year: 2021<br />yearly_rainfall: 3448.2<br />station: Choa Chu Kang (South)<br />station: Choa Chu Kang (South)\",\"year: 2022<br />yearly_rainfall: 2866.6<br />station: Choa Chu Kang (South)<br />station: Choa Chu Kang (South)\",\"year: 2023<br />yearly_rainfall: 3263.6<br />station: Choa Chu Kang (South)<br />station: Choa Chu Kang (South)\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(140,171,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Choa Chu Kang (South)\",\"legendgroup\":\"Choa Chu Kang (South)\",\"showlegend\":true,\"xaxis\":\"x4\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1,2,3,4,5,6,7,8,9,10],\"y\":[2255.8000000000002,1813.2,2379.8000000000002,1879.4000000000001,2888.5,1738.9000000000001,961.60000000000002,2694.8000000000002,3145.6999999999998,3111.4000000000001],\"text\":[\"year: 2014<br />yearly_rainfall: 2255.8<br />station: Clementi<br />station: Clementi\",\"year: 2015<br />yearly_rainfall: 1813.2<br />station: Clementi<br />station: Clementi\",\"year: 2016<br />yearly_rainfall: 2379.8<br />station: Clementi<br />station: Clementi\",\"year: 2017<br />yearly_rainfall: 1879.4<br />station: Clementi<br />station: Clementi\",\"year: 2018<br />yearly_rainfall: 2888.5<br />station: Clementi<br />station: Clementi\",\"year: 2019<br />yearly_rainfall: 1738.9<br />station: Clementi<br />station: Clementi\",\"year: 2020<br />yearly_rainfall:  961.6<br />station: Clementi<br />station: Clementi\",\"year: 2021<br />yearly_rainfall: 2694.8<br />station: Clementi<br />station: Clementi\",\"year: 2022<br />yearly_rainfall: 3145.7<br />station: Clementi<br />station: Clementi\",\"year: 2023<br />yearly_rainfall: 3111.4<br />station: Clementi<br />station: Clementi\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(36,183,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Clementi\",\"legendgroup\":\"Clementi\",\"showlegend\":true,\"xaxis\":\"x5\",\"yaxis\":\"y2\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1,2,3,4,5,6,7,8,9,10],\"y\":[1427.2,1031,1646,2158.1999999999998,1333,1092.3,2040.4000000000001,2551.5999999999999,1886.8,2106.9000000000001],\"text\":[\"year: 2014<br />yearly_rainfall: 1427.2<br />station: East Coast Parkway<br />station: East Coast Parkway\",\"year: 2015<br />yearly_rainfall: 1031.0<br />station: East Coast Parkway<br />station: East Coast Parkway\",\"year: 2016<br />yearly_rainfall: 1646.0<br />station: East Coast Parkway<br />station: East Coast Parkway\",\"year: 2017<br />yearly_rainfall: 2158.2<br />station: East Coast Parkway<br />station: East Coast Parkway\",\"year: 2018<br />yearly_rainfall: 1333.0<br />station: East Coast Parkway<br />station: East Coast Parkway\",\"year: 2019<br />yearly_rainfall: 1092.3<br />station: East Coast Parkway<br />station: East Coast Parkway\",\"year: 2020<br />yearly_rainfall: 2040.4<br />station: East Coast Parkway<br />station: East Coast Parkway\",\"year: 2021<br />yearly_rainfall: 2551.6<br />station: East Coast Parkway<br />station: East Coast Parkway\",\"year: 2022<br />yearly_rainfall: 1886.8<br />station: East Coast Parkway<br />station: East Coast Parkway\",\"year: 2023<br />yearly_rainfall: 2106.9<br />station: East Coast Parkway<br />station: East Coast Parkway\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,190,112,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"East Coast Parkway\",\"legendgroup\":\"East Coast Parkway\",\"showlegend\":true,\"xaxis\":\"x6\",\"yaxis\":\"y2\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1,2,3,4,5,6,7,8,9,10],\"y\":[1070.8,2348,2482,1834.5999999999999,2825.8000000000002,2077.9000000000001,3259.8000000000002,3143.4000000000001,3106.4000000000001,2763],\"text\":[\"year: 2014<br />yearly_rainfall: 1070.8<br />station: Jurong (West)<br />station: Jurong (West)\",\"year: 2015<br />yearly_rainfall: 2348.0<br />station: Jurong (West)<br />station: Jurong (West)\",\"year: 2016<br />yearly_rainfall: 2482.0<br />station: Jurong (West)<br />station: Jurong (West)\",\"year: 2017<br />yearly_rainfall: 1834.6<br />station: Jurong (West)<br />station: Jurong (West)\",\"year: 2018<br />yearly_rainfall: 2825.8<br />station: Jurong (West)<br />station: Jurong (West)\",\"year: 2019<br />yearly_rainfall: 2077.9<br />station: Jurong (West)<br />station: Jurong (West)\",\"year: 2020<br />yearly_rainfall: 3259.8<br />station: Jurong (West)<br />station: Jurong (West)\",\"year: 2021<br />yearly_rainfall: 3143.4<br />station: Jurong (West)<br />station: Jurong (West)\",\"year: 2022<br />yearly_rainfall: 3106.4<br />station: Jurong (West)<br />station: Jurong (West)\",\"year: 2023<br />yearly_rainfall: 2763.0<br />station: Jurong (West)<br />station: Jurong (West)\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,193,171,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Jurong (West)\",\"legendgroup\":\"Jurong (West)\",\"showlegend\":true,\"xaxis\":\"x7\",\"yaxis\":\"y2\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1,2,3,4,5,6,7,8,9,10],\"y\":[1647.8,1752.5999999999999,1564.5999999999999,2099,2482.1999999999998,1520,2476.1999999999998,2137.4000000000001,2528.8000000000002,2192.6999999999998],\"text\":[\"year: 2014<br />yearly_rainfall: 1647.8<br />station: Jurong Island<br />station: Jurong Island\",\"year: 2015<br />yearly_rainfall: 1752.6<br />station: Jurong Island<br />station: Jurong Island\",\"year: 2016<br />yearly_rainfall: 1564.6<br />station: Jurong Island<br />station: Jurong Island\",\"year: 2017<br />yearly_rainfall: 2099.0<br />station: Jurong Island<br />station: Jurong Island\",\"year: 2018<br />yearly_rainfall: 2482.2<br />station: Jurong Island<br />station: Jurong Island\",\"year: 2019<br />yearly_rainfall: 1520.0<br />station: Jurong Island<br />station: Jurong Island\",\"year: 2020<br />yearly_rainfall: 2476.2<br />station: Jurong Island<br />station: Jurong Island\",\"year: 2021<br />yearly_rainfall: 2137.4<br />station: Jurong Island<br />station: Jurong Island\",\"year: 2022<br />yearly_rainfall: 2528.8<br />station: Jurong Island<br />station: Jurong Island\",\"year: 2023<br />yearly_rainfall: 2192.7<br />station: Jurong Island<br />station: Jurong Island\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,187,218,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Jurong Island\",\"legendgroup\":\"Jurong Island\",\"showlegend\":true,\"xaxis\":\"x8\",\"yaxis\":\"y2\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1,2,3,4,5,6,7,8,9,10],\"y\":[2204.5999999999999,1825.5999999999999,1354.5999999999999,2045.5999999999999,2375,1576.5999999999999,2436.8000000000002,2664.5999999999999,2138.5999999999999,2754.8000000000002],\"text\":[\"year: 2014<br />yearly_rainfall: 2204.6<br />station: Newton<br />station: Newton\",\"year: 2015<br />yearly_rainfall: 1825.6<br />station: Newton<br />station: Newton\",\"year: 2016<br />yearly_rainfall: 1354.6<br />station: Newton<br />station: Newton\",\"year: 2017<br />yearly_rainfall: 2045.6<br />station: Newton<br />station: Newton\",\"year: 2018<br />yearly_rainfall: 2375.0<br />station: Newton<br />station: Newton\",\"year: 2019<br />yearly_rainfall: 1576.6<br />station: Newton<br />station: Newton\",\"year: 2020<br />yearly_rainfall: 2436.8<br />station: Newton<br />station: Newton\",\"year: 2021<br />yearly_rainfall: 2664.6<br />station: Newton<br />station: Newton\",\"year: 2022<br />yearly_rainfall: 2138.6<br />station: Newton<br />station: Newton\",\"year: 2023<br />yearly_rainfall: 2754.8<br />station: Newton<br />station: Newton\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,172,252,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Newton\",\"legendgroup\":\"Newton\",\"showlegend\":true,\"xaxis\":\"x9\",\"yaxis\":\"y3\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1,2,3,4,5,6,7,8,9,10],\"y\":[1810.5999999999999,1626.4000000000001,2031,2079.5999999999999,2254.1999999999998,1611.5999999999999,2391.8000000000002,3002.4000000000001,1935.2,2493.6999999999998],\"text\":[\"year: 2014<br />yearly_rainfall: 1810.6<br />station: Pasir Panjang<br />station: Pasir Panjang\",\"year: 2015<br />yearly_rainfall: 1626.4<br />station: Pasir Panjang<br />station: Pasir Panjang\",\"year: 2016<br />yearly_rainfall: 2031.0<br />station: Pasir Panjang<br />station: Pasir Panjang\",\"year: 2017<br />yearly_rainfall: 2079.6<br />station: Pasir Panjang<br />station: Pasir Panjang\",\"year: 2018<br />yearly_rainfall: 2254.2<br />station: Pasir Panjang<br />station: Pasir Panjang\",\"year: 2019<br />yearly_rainfall: 1611.6<br />station: Pasir Panjang<br />station: Pasir Panjang\",\"year: 2020<br />yearly_rainfall: 2391.8<br />station: Pasir Panjang<br />station: Pasir Panjang\",\"year: 2021<br />yearly_rainfall: 3002.4<br />station: Pasir Panjang<br />station: Pasir Panjang\",\"year: 2022<br />yearly_rainfall: 1935.2<br />station: Pasir Panjang<br />station: Pasir Panjang\",\"year: 2023<br />yearly_rainfall: 2493.7<br />station: Pasir Panjang<br />station: Pasir Panjang\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(139,147,255,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Pasir Panjang\",\"legendgroup\":\"Pasir Panjang\",\"showlegend\":true,\"xaxis\":\"x10\",\"yaxis\":\"y3\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1,2,3,4,5,6,7,8,9,10],\"y\":[2118.5999999999999,1574.5999999999999,1679.8,843.20000000000005,1886.5999999999999,1299,2020.8,2687.5999999999999,2665.9000000000001,2624.4000000000001],\"text\":[\"year: 2014<br />yearly_rainfall: 2118.6<br />station: Sentosa Island<br />station: Sentosa Island\",\"year: 2015<br />yearly_rainfall: 1574.6<br />station: Sentosa Island<br />station: Sentosa Island\",\"year: 2016<br />yearly_rainfall: 1679.8<br />station: Sentosa Island<br />station: Sentosa Island\",\"year: 2017<br />yearly_rainfall:  843.2<br />station: Sentosa Island<br />station: Sentosa Island\",\"year: 2018<br />yearly_rainfall: 1886.6<br />station: Sentosa Island<br />station: Sentosa Island\",\"year: 2019<br />yearly_rainfall: 1299.0<br />station: Sentosa Island<br />station: Sentosa Island\",\"year: 2020<br />yearly_rainfall: 2020.8<br />station: Sentosa Island<br />station: Sentosa Island\",\"year: 2021<br />yearly_rainfall: 2687.6<br />station: Sentosa Island<br />station: Sentosa Island\",\"year: 2022<br />yearly_rainfall: 2665.9<br />station: Sentosa Island<br />station: Sentosa Island\",\"year: 2023<br />yearly_rainfall: 2624.4<br />station: Sentosa Island<br />station: Sentosa Island\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(213,117,254,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Sentosa Island\",\"legendgroup\":\"Sentosa Island\",\"showlegend\":true,\"xaxis\":\"x11\",\"yaxis\":\"y3\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1,2,3,4,5,6,7,8,9,10],\"y\":[1950.4000000000001,1584.5999999999999,2249.1999999999998,2695.8000000000002,2178.8000000000002,1638.7,2554.8000000000002,3266.4000000000001,2660.4000000000001,2583],\"text\":[\"year: 2014<br />yearly_rainfall: 1950.4<br />station: Tai Seng<br />station: Tai Seng\",\"year: 2015<br />yearly_rainfall: 1584.6<br />station: Tai Seng<br />station: Tai Seng\",\"year: 2016<br />yearly_rainfall: 2249.2<br />station: Tai Seng<br />station: Tai Seng\",\"year: 2017<br />yearly_rainfall: 2695.8<br />station: Tai Seng<br />station: Tai Seng\",\"year: 2018<br />yearly_rainfall: 2178.8<br />station: Tai Seng<br />station: Tai Seng\",\"year: 2019<br />yearly_rainfall: 1638.7<br />station: Tai Seng<br />station: Tai Seng\",\"year: 2020<br />yearly_rainfall: 2554.8<br />station: Tai Seng<br />station: Tai Seng\",\"year: 2021<br />yearly_rainfall: 3266.4<br />station: Tai Seng<br />station: Tai Seng\",\"year: 2022<br />yearly_rainfall: 2660.4<br />station: Tai Seng<br />station: Tai Seng\",\"year: 2023<br />yearly_rainfall: 2583.0<br />station: Tai Seng<br />station: Tai Seng\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(249,98,221,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Tai Seng\",\"legendgroup\":\"Tai Seng\",\"showlegend\":true,\"xaxis\":\"x12\",\"yaxis\":\"y3\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1,2,3,4,5,6,7,8,9,10],\"y\":[1751.8,2009,1812.2,2285.4000000000001,2396.8000000000002,1648.5999999999999,3377,2775.5,2636.5999999999999,2895.3000000000002],\"text\":[\"year: 2014<br />yearly_rainfall: 1751.8<br />station: Tuas South<br />station: Tuas South\",\"year: 2015<br />yearly_rainfall: 2009.0<br />station: Tuas South<br />station: Tuas South\",\"year: 2016<br />yearly_rainfall: 1812.2<br />station: Tuas South<br />station: Tuas South\",\"year: 2017<br />yearly_rainfall: 2285.4<br />station: Tuas South<br />station: Tuas South\",\"year: 2018<br />yearly_rainfall: 2396.8<br />station: Tuas South<br />station: Tuas South\",\"year: 2019<br />yearly_rainfall: 1648.6<br />station: Tuas South<br />station: Tuas South\",\"year: 2020<br />yearly_rainfall: 3377.0<br />station: Tuas South<br />station: Tuas South\",\"year: 2021<br />yearly_rainfall: 2775.5<br />station: Tuas South<br />station: Tuas South\",\"year: 2022<br />yearly_rainfall: 2636.6<br />station: Tuas South<br />station: Tuas South\",\"year: 2023<br />yearly_rainfall: 2895.3<br />station: Tuas South<br />station: Tuas South\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,101,172,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Tuas South\",\"legendgroup\":\"Tuas South\",\"showlegend\":true,\"xaxis\":\"x13\",\"yaxis\":\"y4\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":54.964992389649936,\"r\":7.3059360730593621,\"b\":51.385083713850847,\"l\":48.949771689497723},\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"title\":{\"text\":\"Yearly rainfall across weather stations from 2014 to 2023\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":17.534246575342465},\"x\":0,\"xref\":\"paper\"},\"xaxis\":{\"domain\":[0,0.24315068493150685],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.40000000000000002,10.6],\"tickmode\":\"array\",\"ticktext\":[\"2014\",\"2015\",\"2016\",\"2017\",\"2018\",\"2019\",\"2020\",\"2021\",\"2022\",\"2023\"],\"tickvals\":[1,2,3,4,5,6.0000000000000009,7,8,9,10],\"categoryorder\":\"array\",\"categoryarray\":[\"2014\",\"2015\",\"2016\",\"2017\",\"2018\",\"2019\",\"2020\",\"2021\",\"2022\",\"2023\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-90,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y\",\"title\":\"\",\"hoverformat\":\".2f\"},\"annotations\":[{\"text\":\"Year\",\"x\":0.5,\"y\":0,\"showarrow\":false,\"ax\":0,\"ay\":0,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"xref\":\"paper\",\"yref\":\"paper\",\"textangle\":-0,\"xanchor\":\"center\",\"yanchor\":\"top\",\"annotationType\":\"axis\",\"yshift\":-33.607305936073061},{\"text\":\"Rainfall volume (mm)\",\"x\":0,\"y\":0.5,\"showarrow\":false,\"ax\":0,\"ay\":0,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"xref\":\"paper\",\"yref\":\"paper\",\"textangle\":-90,\"xanchor\":\"right\",\"yanchor\":\"center\",\"annotationType\":\"axis\",\"xshift\":-33.607305936073061},{\"text\":\"Admiralty\",\"x\":0.12157534246575342,\"y\":1,\"showarrow\":false,\"ax\":0,\"ay\":0,\"font\":{\"color\":\"rgba(26,26,26,1)\",\"family\":\"\",\"size\":11.68949771689498},\"xref\":\"paper\",\"yref\":\"paper\",\"textangle\":-0,\"xanchor\":\"center\",\"yanchor\":\"bottom\"},{\"text\":\"Ang Mo Kio\",\"x\":0.375,\"y\":1,\"showarrow\":false,\"ax\":0,\"ay\":0,\"font\":{\"color\":\"rgba(26,26,26,1)\",\"family\":\"\",\"size\":11.68949771689498},\"xref\":\"paper\",\"yref\":\"paper\",\"textangle\":-0,\"xanchor\":\"center\",\"yanchor\":\"bottom\"},{\"text\":\"Changi\",\"x\":0.625,\"y\":1,\"showarrow\":false,\"ax\":0,\"ay\":0,\"font\":{\"color\":\"rgba(26,26,26,1)\",\"family\":\"\",\"size\":11.68949771689498},\"xref\":\"paper\",\"yref\":\"paper\",\"textangle\":-0,\"xanchor\":\"center\",\"yanchor\":\"bottom\"},{\"text\":\"Choa Chu Kang (South)\",\"x\":0.87842465753424659,\"y\":1,\"showarrow\":false,\"ax\":0,\"ay\":0,\"font\":{\"color\":\"rgba(26,26,26,1)\",\"family\":\"\",\"size\":11.68949771689498},\"xref\":\"paper\",\"yref\":\"paper\",\"textangle\":-0,\"xanchor\":\"center\",\"yanchor\":\"bottom\"},{\"text\":\"Clementi\",\"x\":0.12157534246575342,\"y\":0.69703196347031959,\"showarrow\":false,\"ax\":0,\"ay\":0,\"font\":{\"color\":\"rgba(26,26,26,1)\",\"family\":\"\",\"size\":11.68949771689498},\"xref\":\"paper\",\"yref\":\"paper\",\"textangle\":-0,\"xanchor\":\"center\",\"yanchor\":\"bottom\"},{\"text\":\"East Coast Parkway\",\"x\":0.375,\"y\":0.69703196347031959,\"showarrow\":false,\"ax\":0,\"ay\":0,\"font\":{\"color\":\"rgba(26,26,26,1)\",\"family\":\"\",\"size\":11.68949771689498},\"xref\":\"paper\",\"yref\":\"paper\",\"textangle\":-0,\"xanchor\":\"center\",\"yanchor\":\"bottom\"},{\"text\":\"Jurong (West)\",\"x\":0.625,\"y\":0.69703196347031959,\"showarrow\":false,\"ax\":0,\"ay\":0,\"font\":{\"color\":\"rgba(26,26,26,1)\",\"family\":\"\",\"size\":11.68949771689498},\"xref\":\"paper\",\"yref\":\"paper\",\"textangle\":-0,\"xanchor\":\"center\",\"yanchor\":\"bottom\"},{\"text\":\"Jurong Island\",\"x\":0.87842465753424659,\"y\":0.69703196347031959,\"showarrow\":false,\"ax\":0,\"ay\":0,\"font\":{\"color\":\"rgba(26,26,26,1)\",\"family\":\"\",\"size\":11.68949771689498},\"xref\":\"paper\",\"yref\":\"paper\",\"textangle\":-0,\"xanchor\":\"center\",\"yanchor\":\"bottom\"},{\"text\":\"Newton\",\"x\":0.12157534246575342,\"y\":0.44703196347031959,\"showarrow\":false,\"ax\":0,\"ay\":0,\"font\":{\"color\":\"rgba(26,26,26,1)\",\"family\":\"\",\"size\":11.68949771689498},\"xref\":\"paper\",\"yref\":\"paper\",\"textangle\":-0,\"xanchor\":\"center\",\"yanchor\":\"bottom\"},{\"text\":\"Pasir Panjang\",\"x\":0.375,\"y\":0.44703196347031959,\"showarrow\":false,\"ax\":0,\"ay\":0,\"font\":{\"color\":\"rgba(26,26,26,1)\",\"family\":\"\",\"size\":11.68949771689498},\"xref\":\"paper\",\"yref\":\"paper\",\"textangle\":-0,\"xanchor\":\"center\",\"yanchor\":\"bottom\"},{\"text\":\"Sentosa Island\",\"x\":0.625,\"y\":0.44703196347031959,\"showarrow\":false,\"ax\":0,\"ay\":0,\"font\":{\"color\":\"rgba(26,26,26,1)\",\"family\":\"\",\"size\":11.68949771689498},\"xref\":\"paper\",\"yref\":\"paper\",\"textangle\":-0,\"xanchor\":\"center\",\"yanchor\":\"bottom\"},{\"text\":\"Tai Seng\",\"x\":0.87842465753424659,\"y\":0.44703196347031959,\"showarrow\":false,\"ax\":0,\"ay\":0,\"font\":{\"color\":\"rgba(26,26,26,1)\",\"family\":\"\",\"size\":11.68949771689498},\"xref\":\"paper\",\"yref\":\"paper\",\"textangle\":-0,\"xanchor\":\"center\",\"yanchor\":\"bottom\"},{\"text\":\"Tuas South\",\"x\":0.12157534246575342,\"y\":0.19703196347031962,\"showarrow\":false,\"ax\":0,\"ay\":0,\"font\":{\"color\":\"rgba(26,26,26,1)\",\"family\":\"\",\"size\":11.68949771689498},\"xref\":\"paper\",\"yref\":\"paper\",\"textangle\":-0,\"xanchor\":\"center\",\"yanchor\":\"bottom\"}],\"yaxis\":{\"domain\":[0.80296803652968041,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[712.95000000000005,3578.4499999999998],\"tickmode\":\"array\",\"ticktext\":[\"1000\",\"1500\",\"2000\",\"2500\",\"3000\",\"3500\"],\"tickvals\":[1000,1500,2000,2500,3000,3500],\"categoryorder\":\"array\",\"categoryarray\":[\"1000\",\"1500\",\"2000\",\"2500\",\"3000\",\"3500\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"x\",\"title\":\"\",\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":0.24315068493150685,\"y0\":0.80296803652968041,\"y1\":1},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":0.24315068493150685,\"y0\":0,\"y1\":23.37899543378996,\"yanchor\":1,\"ysizemode\":\"pixel\"},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0.25684931506849318,\"x1\":0.49315068493150682,\"y0\":0.80296803652968041,\"y1\":1},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0.25684931506849318,\"x1\":0.49315068493150682,\"y0\":0,\"y1\":23.37899543378996,\"yanchor\":1,\"ysizemode\":\"pixel\"},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0.50684931506849318,\"x1\":0.74315068493150682,\"y0\":0.80296803652968041,\"y1\":1},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0.50684931506849318,\"x1\":0.74315068493150682,\"y0\":0,\"y1\":23.37899543378996,\"yanchor\":1,\"ysizemode\":\"pixel\"},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0.75684931506849318,\"x1\":1,\"y0\":0.80296803652968041,\"y1\":1},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0.75684931506849318,\"x1\":1,\"y0\":0,\"y1\":23.37899543378996,\"yanchor\":1,\"ysizemode\":\"pixel\"},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":0.24315068493150685,\"y0\":0.55296803652968041,\"y1\":0.69703196347031959},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":0.24315068493150685,\"y0\":0,\"y1\":23.37899543378996,\"yanchor\":0.69703196347031959,\"ysizemode\":\"pixel\"},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0.25684931506849318,\"x1\":0.49315068493150682,\"y0\":0.55296803652968041,\"y1\":0.69703196347031959},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0.25684931506849318,\"x1\":0.49315068493150682,\"y0\":0,\"y1\":23.37899543378996,\"yanchor\":0.69703196347031959,\"ysizemode\":\"pixel\"},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0.50684931506849318,\"x1\":0.74315068493150682,\"y0\":0.55296803652968041,\"y1\":0.69703196347031959},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0.50684931506849318,\"x1\":0.74315068493150682,\"y0\":0,\"y1\":23.37899543378996,\"yanchor\":0.69703196347031959,\"ysizemode\":\"pixel\"},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0.75684931506849318,\"x1\":1,\"y0\":0.55296803652968041,\"y1\":0.69703196347031959},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0.75684931506849318,\"x1\":1,\"y0\":0,\"y1\":23.37899543378996,\"yanchor\":0.69703196347031959,\"ysizemode\":\"pixel\"},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":0.24315068493150685,\"y0\":0.30296803652968041,\"y1\":0.44703196347031959},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":0.24315068493150685,\"y0\":0,\"y1\":23.37899543378996,\"yanchor\":0.44703196347031959,\"ysizemode\":\"pixel\"},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0.25684931506849318,\"x1\":0.49315068493150682,\"y0\":0.30296803652968041,\"y1\":0.44703196347031959},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0.25684931506849318,\"x1\":0.49315068493150682,\"y0\":0,\"y1\":23.37899543378996,\"yanchor\":0.44703196347031959,\"ysizemode\":\"pixel\"},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0.50684931506849318,\"x1\":0.74315068493150682,\"y0\":0.30296803652968041,\"y1\":0.44703196347031959},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0.50684931506849318,\"x1\":0.74315068493150682,\"y0\":0,\"y1\":23.37899543378996,\"yanchor\":0.44703196347031959,\"ysizemode\":\"pixel\"},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0.75684931506849318,\"x1\":1,\"y0\":0.30296803652968041,\"y1\":0.44703196347031959},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0.75684931506849318,\"x1\":1,\"y0\":0,\"y1\":23.37899543378996,\"yanchor\":0.44703196347031959,\"ysizemode\":\"pixel\"},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":0.24315068493150685,\"y0\":0,\"y1\":0.19703196347031962},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":0.24315068493150685,\"y0\":0,\"y1\":23.37899543378996,\"yanchor\":0.19703196347031962,\"ysizemode\":\"pixel\"}],\"xaxis2\":{\"type\":\"linear\",\"autorange\":false,\"range\":[0.40000000000000002,10.6],\"tickmode\":\"array\",\"ticktext\":[\"2014\",\"2015\",\"2016\",\"2017\",\"2018\",\"2019\",\"2020\",\"2021\",\"2022\",\"2023\"],\"tickvals\":[1,2,3,4,5,6.0000000000000009,7,8,9,10],\"categoryorder\":\"array\",\"categoryarray\":[\"2014\",\"2015\",\"2016\",\"2017\",\"2018\",\"2019\",\"2020\",\"2021\",\"2022\",\"2023\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-90,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"domain\":[0.25684931506849318,0.49315068493150682],\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y\",\"title\":\"\",\"hoverformat\":\".2f\"},\"xaxis3\":{\"type\":\"linear\",\"autorange\":false,\"range\":[0.40000000000000002,10.6],\"tickmode\":\"array\",\"ticktext\":[\"2014\",\"2015\",\"2016\",\"2017\",\"2018\",\"2019\",\"2020\",\"2021\",\"2022\",\"2023\"],\"tickvals\":[1,2,3,4,5,6.0000000000000009,7,8,9,10],\"categoryorder\":\"array\",\"categoryarray\":[\"2014\",\"2015\",\"2016\",\"2017\",\"2018\",\"2019\",\"2020\",\"2021\",\"2022\",\"2023\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-90,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"domain\":[0.50684931506849318,0.74315068493150682],\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y\",\"title\":\"\",\"hoverformat\":\".2f\"},\"xaxis4\":{\"type\":\"linear\",\"autorange\":false,\"range\":[0.40000000000000002,10.6],\"tickmode\":\"array\",\"ticktext\":[\"2014\",\"2015\",\"2016\",\"2017\",\"2018\",\"2019\",\"2020\",\"2021\",\"2022\",\"2023\"],\"tickvals\":[1,2,3,4,5,6.0000000000000009,7,8,9,10],\"categoryorder\":\"array\",\"categoryarray\":[\"2014\",\"2015\",\"2016\",\"2017\",\"2018\",\"2019\",\"2020\",\"2021\",\"2022\",\"2023\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-90,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"domain\":[0.75684931506849318,1],\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y\",\"title\":\"\",\"hoverformat\":\".2f\"},\"xaxis5\":{\"type\":\"linear\",\"autorange\":false,\"range\":[0.40000000000000002,10.6],\"tickmode\":\"array\",\"ticktext\":[\"2014\",\"2015\",\"2016\",\"2017\",\"2018\",\"2019\",\"2020\",\"2021\",\"2022\",\"2023\"],\"tickvals\":[1,2,3,4,5,6.0000000000000009,7,8,9,10],\"categoryorder\":\"array\",\"categoryarray\":[\"2014\",\"2015\",\"2016\",\"2017\",\"2018\",\"2019\",\"2020\",\"2021\",\"2022\",\"2023\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-90,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"domain\":[0,0.24315068493150685],\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y2\",\"title\":\"\",\"hoverformat\":\".2f\"},\"yaxis2\":{\"type\":\"linear\",\"autorange\":false,\"range\":[712.95000000000005,3578.4499999999998],\"tickmode\":\"array\",\"ticktext\":[\"1000\",\"1500\",\"2000\",\"2500\",\"3000\",\"3500\"],\"tickvals\":[1000,1500,2000,2500,3000,3500],\"categoryorder\":\"array\",\"categoryarray\":[\"1000\",\"1500\",\"2000\",\"2500\",\"3000\",\"3500\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"domain\":[0.55296803652968041,0.69703196347031959],\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"x\",\"title\":\"\",\"hoverformat\":\".2f\"},\"xaxis6\":{\"type\":\"linear\",\"autorange\":false,\"range\":[0.40000000000000002,10.6],\"tickmode\":\"array\",\"ticktext\":[\"2014\",\"2015\",\"2016\",\"2017\",\"2018\",\"2019\",\"2020\",\"2021\",\"2022\",\"2023\"],\"tickvals\":[1,2,3,4,5,6.0000000000000009,7,8,9,10],\"categoryorder\":\"array\",\"categoryarray\":[\"2014\",\"2015\",\"2016\",\"2017\",\"2018\",\"2019\",\"2020\",\"2021\",\"2022\",\"2023\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-90,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"domain\":[0.25684931506849318,0.49315068493150682],\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y2\",\"title\":\"\",\"hoverformat\":\".2f\"},\"xaxis7\":{\"type\":\"linear\",\"autorange\":false,\"range\":[0.40000000000000002,10.6],\"tickmode\":\"array\",\"ticktext\":[\"2014\",\"2015\",\"2016\",\"2017\",\"2018\",\"2019\",\"2020\",\"2021\",\"2022\",\"2023\"],\"tickvals\":[1,2,3,4,5,6.0000000000000009,7,8,9,10],\"categoryorder\":\"array\",\"categoryarray\":[\"2014\",\"2015\",\"2016\",\"2017\",\"2018\",\"2019\",\"2020\",\"2021\",\"2022\",\"2023\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-90,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"domain\":[0.50684931506849318,0.74315068493150682],\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y2\",\"title\":\"\",\"hoverformat\":\".2f\"},\"xaxis8\":{\"type\":\"linear\",\"autorange\":false,\"range\":[0.40000000000000002,10.6],\"tickmode\":\"array\",\"ticktext\":[\"2014\",\"2015\",\"2016\",\"2017\",\"2018\",\"2019\",\"2020\",\"2021\",\"2022\",\"2023\"],\"tickvals\":[1,2,3,4,5,6.0000000000000009,7,8,9,10],\"categoryorder\":\"array\",\"categoryarray\":[\"2014\",\"2015\",\"2016\",\"2017\",\"2018\",\"2019\",\"2020\",\"2021\",\"2022\",\"2023\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-90,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"domain\":[0.75684931506849318,1],\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y2\",\"title\":\"\",\"hoverformat\":\".2f\"},\"xaxis9\":{\"type\":\"linear\",\"autorange\":false,\"range\":[0.40000000000000002,10.6],\"tickmode\":\"array\",\"ticktext\":[\"2014\",\"2015\",\"2016\",\"2017\",\"2018\",\"2019\",\"2020\",\"2021\",\"2022\",\"2023\"],\"tickvals\":[1,2,3,4,5,6.0000000000000009,7,8,9,10],\"categoryorder\":\"array\",\"categoryarray\":[\"2014\",\"2015\",\"2016\",\"2017\",\"2018\",\"2019\",\"2020\",\"2021\",\"2022\",\"2023\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-90,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"domain\":[0,0.24315068493150685],\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y3\",\"title\":\"\",\"hoverformat\":\".2f\"},\"yaxis3\":{\"type\":\"linear\",\"autorange\":false,\"range\":[712.95000000000005,3578.4499999999998],\"tickmode\":\"array\",\"ticktext\":[\"1000\",\"1500\",\"2000\",\"2500\",\"3000\",\"3500\"],\"tickvals\":[1000,1500,2000,2500,3000,3500],\"categoryorder\":\"array\",\"categoryarray\":[\"1000\",\"1500\",\"2000\",\"2500\",\"3000\",\"3500\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"domain\":[0.30296803652968041,0.44703196347031959],\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"x\",\"title\":\"\",\"hoverformat\":\".2f\"},\"xaxis10\":{\"type\":\"linear\",\"autorange\":false,\"range\":[0.40000000000000002,10.6],\"tickmode\":\"array\",\"ticktext\":[\"2014\",\"2015\",\"2016\",\"2017\",\"2018\",\"2019\",\"2020\",\"2021\",\"2022\",\"2023\"],\"tickvals\":[1,2,3,4,5,6.0000000000000009,7,8,9,10],\"categoryorder\":\"array\",\"categoryarray\":[\"2014\",\"2015\",\"2016\",\"2017\",\"2018\",\"2019\",\"2020\",\"2021\",\"2022\",\"2023\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-90,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"domain\":[0.25684931506849318,0.49315068493150682],\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y3\",\"title\":\"\",\"hoverformat\":\".2f\"},\"xaxis11\":{\"type\":\"linear\",\"autorange\":false,\"range\":[0.40000000000000002,10.6],\"tickmode\":\"array\",\"ticktext\":[\"2014\",\"2015\",\"2016\",\"2017\",\"2018\",\"2019\",\"2020\",\"2021\",\"2022\",\"2023\"],\"tickvals\":[1,2,3,4,5,6.0000000000000009,7,8,9,10],\"categoryorder\":\"array\",\"categoryarray\":[\"2014\",\"2015\",\"2016\",\"2017\",\"2018\",\"2019\",\"2020\",\"2021\",\"2022\",\"2023\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-90,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"domain\":[0.50684931506849318,0.74315068493150682],\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y3\",\"title\":\"\",\"hoverformat\":\".2f\"},\"xaxis12\":{\"type\":\"linear\",\"autorange\":false,\"range\":[0.40000000000000002,10.6],\"tickmode\":\"array\",\"ticktext\":[\"2014\",\"2015\",\"2016\",\"2017\",\"2018\",\"2019\",\"2020\",\"2021\",\"2022\",\"2023\"],\"tickvals\":[1,2,3,4,5,6.0000000000000009,7,8,9,10],\"categoryorder\":\"array\",\"categoryarray\":[\"2014\",\"2015\",\"2016\",\"2017\",\"2018\",\"2019\",\"2020\",\"2021\",\"2022\",\"2023\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-90,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"domain\":[0.75684931506849318,1],\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y3\",\"title\":\"\",\"hoverformat\":\".2f\"},\"xaxis13\":{\"type\":\"linear\",\"autorange\":false,\"range\":[0.40000000000000002,10.6],\"tickmode\":\"array\",\"ticktext\":[\"2014\",\"2015\",\"2016\",\"2017\",\"2018\",\"2019\",\"2020\",\"2021\",\"2022\",\"2023\"],\"tickvals\":[1,2,3,4,5,6.0000000000000009,7,8,9,10],\"categoryorder\":\"array\",\"categoryarray\":[\"2014\",\"2015\",\"2016\",\"2017\",\"2018\",\"2019\",\"2020\",\"2021\",\"2022\",\"2023\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-90,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"domain\":[0,0.24315068493150685],\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y4\",\"title\":\"\",\"hoverformat\":\".2f\"},\"yaxis4\":{\"type\":\"linear\",\"autorange\":false,\"range\":[712.95000000000005,3578.4499999999998],\"tickmode\":\"array\",\"ticktext\":[\"1000\",\"1500\",\"2000\",\"2500\",\"3000\",\"3500\"],\"tickvals\":[1000,1500,2000,2500,3000,3500],\"categoryorder\":\"array\",\"categoryarray\":[\"1000\",\"1500\",\"2000\",\"2500\",\"3000\",\"3500\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"domain\":[0,0.19703196347031962],\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"x\",\"title\":\"\",\"hoverformat\":\".2f\"},\"showlegend\":true,\"legend\":{\"bgcolor\":null,\"bordercolor\":null,\"borderwidth\":0,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498},\"title\":{\"text\":\"station\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}}},\"hovermode\":\"closest\",\"width\":800,\"height\":600,\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"7ae07219ac5\":{\"x\":{},\"y\":{},\"colour\":{},\"type\":\"scatter\"}},\"cur_data\":\"7ae07219ac5\",\"visdat\":{\"7ae07219ac5\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\nOver the years, across the 13 weather stations, the rainfall volume is observed to have increased albeit by different intensities. We need to examine if the differences are statistically different.\n\nBefore we do so**,** we will need to determine whether the rainfall for each year follows a normal or non-normal distribution and we visualise the distribution of rainfall using ridgeline plots, using the code chunk below.\n\n::: panel-tabset\n## Zoomed-in plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\np2 <- ggplot(historical_rainfall, \n       aes(x = daily_rainfall_total, \n           y = year, \n           fill = 0.5 - abs(0.5-stat(ecdf)))) +\n  stat_density_ridges(geom = \"density_ridges_gradient\", \n                      calc_ecdf = TRUE) +\n  scale_fill_viridis_c(name = \"Tail probability\",\n                       direction = -1,\n                       option=\"turbo\")+\n  facet_wrap(~station) + \n  theme_ridges(font_size = 25)+\n  coord_cartesian(xlim = c(0,50))+\n  labs(title=\"Distribution of Yearly Rainfall from 2014 to 2023 (zoomed in)\",\n       y=\"Station\",\n       x=\"Rainfall Volume (mm)\")\n\np2\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex4_files/figure-html/unnamed-chunk-12-1.png){width=2880}\n:::\n:::\n\n\n## Full plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\np3 <- ggplot(historical_rainfall, \n       aes(x = daily_rainfall_total, \n           y = year, \n           fill = 0.5 - abs(0.5-stat(ecdf)))) +\n  stat_density_ridges(geom = \"density_ridges_gradient\", \n                      calc_ecdf = TRUE) +\n  scale_fill_viridis_c(name = \"Tail probability\",\n                       direction = -1,\n                       option=\"turbo\")+\n  facet_wrap(~station) + \n  theme_ridges(font_size = 25)+\n  labs(title=\"Distribution of Yearly Rainfall from 2014 to 2023\",\n       y=\"Station\",\n       x=\"Rainfall Volume (mm)\")\n\np3\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex4_files/figure-html/unnamed-chunk-13-1.png){width=2880}\n:::\n:::\n\n:::\n\nAs the distribution of rainfall is not normal, I will utilise non-parametric test.\n\n**The hypothesis is as follows:**\n\n*H~0~: There is no difference between median rainfall across 10 years.*\n\n*H~1~: There is a difference between median rainfall across 10 years.*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggbetweenstats(\n  data = historical_rainfall_year,\n  x = year, \n  y = yearly_rainfall,\n  type = \"np\",\n  messages = FALSE,\n  title=\"Distribution of Rainfall across 10 years (2014 to 2023)\"\n)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex4_files/figure-html/unnamed-chunk-14-1.png){width=1152}\n:::\n:::\n\n\n## 5.3 CDA #3 - Are there certain locations “drier” or “wetter”/ “hotter” or “cooler”?\n\n**The hypothesis is as follows:**\n\n*H~0~: There is no difference between median yearly rainfall across weather stations.*\n\n*H~1~: There is a difference between median yearly rainfall across weather stations.*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggbetweenstats(\n  data = historical_rainfall_year,\n  x = station, \n  y = yearly_rainfall,\n  type = \"np\",\n  messages = FALSE,\n  title=\"Distribution of Yearly Rainfall by Station\"\n)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex4_files/figure-html/unnamed-chunk-15-1.png){width=1152}\n:::\n:::\n",
    "supporting": [
      "Take-home_Ex4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/plotly-binding-4.10.4/plotly.js\"></script>\n<script src=\"../../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\n<link href=\"../../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}